services:
  # Web Service with SQLite
  - type: web
    name: scoreset
    env: python
    plan: free
    buildCommand: cd score_set/SHACK360_pkg && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd score_set/SHACK360_pkg && gunicorn counter.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,scoreset.onrender.com
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
