services:
  - type: web
    name: score-set
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_admin
    startCommand: cd counter && python -m gunicorn wsgi:application --bind 0.0.0.0:$PORT
    rootDir: score_set/SHACK360_pkg
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: admin@example.com
