"""
Django settings for counter project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: require SECRET_KEY from environment in production
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-in-production')

# DEBUG should be controlled by environment; default to True for development
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Configure allowed hosts via env var (comma-separated). Default to localhost for dev.
_allowed = os.environ.get('ALLOWED_HOSTS', '')
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] if DEBUG else []

# Add Vercel domain to CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'https://counter-icb6s5kdx-awas-projects-f82bcad8.vercel.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'theme',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Security headers middleware adds CSP, Referrer-Policy, Permissions-Policy
    "counter.middleware.security_headers.SecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Force no-cache headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = "counter.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "theme" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "counter.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

# Only use dj_database_url if we have a valid PostgreSQL URL
if DATABASE_URL and DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=0, conn_health_checks=False)
    }
    # Supabase connection pooler configuration
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
    DATABASES['default']['CONN_MAX_AGE'] = 0
    DATABASES['default']['CONN_HEALTH_CHECKS'] = False
    DATABASES['default']['ATOMIC_REQUESTS'] = False
    DATABASES['default']['AUTOCOMMIT'] = True
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'connect_timeout': 10,
        'options': '-c statement_timeout=30000',
    }
else:
    # Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_SECURE = not DEBUG  # Use secure session cookies in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Basic throttling to reduce brute force / abuse risk
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('DRF_THROTTLE_ANON', '100/day'),
        'user': os.environ.get('DRF_THROTTLE_USER', '1000/day'),
    },
}

# Allow switching away from DB-backed sessions via an environment variable.
# This is a short-term mitigation when the database is unavailable (e.g. while
# you debug Supabase connection issues). In production you should use a
# persistent session store and ensure DATABASE_URL is correct.
USE_COOKIE_SESSIONS = os.environ.get('USE_COOKIE_SESSIONS', '').lower() in ('1', 'true', 'yes')
if USE_COOKIE_SESSIONS:
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
else:
    SESSION_ENGINE = os.environ.get('SESSION_ENGINE', 'django.contrib.sessions.backends.db')

# HTTP Strict Transport Security and SSL redirect settings (configure via env in production)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes') and not DEBUG

# Master key for encrypting sensitive fields (Fernet URL-safe base64 key)
# Optional - only required if using encrypted fields
MASTER_KEY = os.environ.get('MASTER_KEY', '')

# Content Security Policy and related header defaults. Adjust in environment as needed.
# By default allow self and required CDNs used by the frontend (fonts.googleapis and tailwind CDN).
_csp_script_src = ["'self'", 'https://cdn.tailwindcss.com']
_csp_style_src = ["'self'", 'https://fonts.googleapis.com', "'unsafe-inline'"]
_csp_font_src = ["'self'", 'https://fonts.gstatic.com', 'data:']
_csp_img_src = ["'self'", 'data:']
_csp_connect_src = ["'self'", 'https://*']

CSP_HEADER = os.environ.get('CSP_HEADER') or (
    ' '.join([
        "default-src 'self';",
        'script-src ' + ' '.join(_csp_script_src) + ';',
        'style-src ' + ' '.join(_csp_style_src) + ';',
        'font-src ' + ' '.join(_csp_font_src) + ';',
        'img-src ' + ' '.join(_csp_img_src) + ';',
        'connect-src ' + ' '.join(_csp_connect_src) + ';',
    ])
)

REFERRER_POLICY = os.environ.get('REFERRER_POLICY', 'same-origin')
PERMISSIONS_POLICY = os.environ.get('PERMISSIONS_POLICY', "geolocation=(), microphone=()")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'theme' / 'static',
]

# Allow CSP to include unpkg.com for lucide icons and Alpinejs
_csp_script_src.extend(['https://unpkg.com', 'https://cdn.jsdelivr.net', "'unsafe-inline'"])